DROP DATABASE IF EXISTS PROXIMAFECHA;
CREATE DATABASE  PROXIMAFECHA;
USE PROXIMAFECHA;

-- -----------------------------------------------------
-- Table DEPORTES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DEPORTES (
  DEPORTE_ID INT NOT NULL AUTO_INCREMENT,
  DESCRIPCION VARCHAR(45) NULL,
  MAX_JUGADORES INT(2) NULL,
  PRIMARY KEY (DEPORTE_ID))
;


-- -----------------------------------------------------
-- Table TIPOS_TORNEO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TIPOS_TORNEO (
  TIPO_TORNEO_ID VARCHAR(1) NOT NULL,
  DESCRIPCION VARCHAR(45) NOT NULL,
  PRIMARY KEY (TIPO_TORNEO_ID))
;


-- -----------------------------------------------------
-- Table PAISES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PAISES (
  PAIS_ID VARCHAR(3) NOT NULL,
  PAIS VARCHAR(45) NOT NULL,
  ISO VARCHAR(2) NOT NULL,
  PRIMARY KEY (PAIS_ID))
;


-- -----------------------------------------------------
-- Table PROVINCIAS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PROVINCIAS (
  PAIS_ID VARCHAR(3) NOT NULL,
  PROVINCIA_ID VARCHAR(3) NOT NULL,
  PROVINCIA VARCHAR(45) NOT NULL,
  PRIMARY KEY (PAIS_ID, PROVINCIA_ID),
  CONSTRAINT fk_PROVINCIAS_PAISES1
    FOREIGN KEY (PAIS_ID)
    REFERENCES PAISES (PAIS_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table SEDES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS SEDES (
  SEDE_ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(45) NOT NULL,
  PAIS_ID VARCHAR(3) NOT NULL,
  PROVINCIA_ID VARCHAR(3) NOT NULL,
  CODIGO_POSTAL VARCHAR(10) NOT NULL,
  CALLE VARCHAR(45) NOT NULL,
  ALTURA INT(5) NOT NULL,
  TELEFONO VARCHAR(20)  NOT NULL,
  DETALLES VARCHAR(200) NULL,
  PRIMARY KEY (SEDE_ID),
  INDEX fk_SEDES_PROVINCIAS1_idx (PAIS_ID ASC, PROVINCIA_ID ASC),
  CONSTRAINT fk_SEDES_PROVINCIAS1
    FOREIGN KEY (PAIS_ID , PROVINCIA_ID)
    REFERENCES PROVINCIAS (PAIS_ID , PROVINCIA_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table TORNEOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TORNEOS (
  TORNEO_ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(60) NOT NULL,
  DEPORTE_ID INT NOT NULL,
  TIPO_TORNEO_ID VARCHAR(1) NOT NULL,
  CANTIDAD_EQUIPOS INT(2) NOT NULL,
  FECHA_INICIO DATE NULL,
  SEDE_ID INT NULL,
  PRIMARY KEY (TORNEO_ID),
  INDEX fk_TORNEOS_TIPOS_TORNEO1_idx (DEPORTE_ID ASC),
  INDEX fk_TORNEOS_TIPOS_TORNEO2_idx (TIPO_TORNEO_ID ASC),
  INDEX fk_TORNEOS_SEDES1_idx (SEDE_ID ASC),
  CONSTRAINT fk_TORNEOS_TIPOS_TORNEO1
    FOREIGN KEY (DEPORTE_ID)
    REFERENCES DEPORTES (DEPORTE_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_TORNEOS_TIPOS_TORNEO2
    FOREIGN KEY (TIPO_TORNEO_ID)
    REFERENCES TIPOS_TORNEO (TIPO_TORNEO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_TORNEOS_SEDES1
    FOREIGN KEY (SEDE_ID)
    REFERENCES SEDES (SEDE_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table USUARIOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS USUARIOS (
  USUARIO_ID VARCHAR(45) NOT NULL,
  PASSWORD VARCHAR(256) NOT NULL,
  NOMBRE VARCHAR(45) NOT NULL,
  APELLIDO VARCHAR(45) NOT NULL,
  EMAIL VARCHAR(45)  NULL,
  ACTIVO VARCHAR(1) NOT NULL DEFAULT 'Y',
  TELEFONO VARCHAR(20) NULL,
  ULTIMA_VEZ_ONLINE DATE NULL,
  PRIMARY KEY (USUARIO_ID))
;


-- -----------------------------------------------------
-- Table EQUIPOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS EQUIPOS (
  EQUIPO_ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(60) NOT NULL,
  CAPITAN_ID VARCHAR(45) NOT NULL,
  ACTIVO VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (EQUIPO_ID),
  INDEX fk_EQUIPOS_USUARIOS_idx (CAPITAN_ID ASC),
  CONSTRAINT fk_EQUIPOS_USUARIOS
    FOREIGN KEY (CAPITAN_ID)
    REFERENCES USUARIOS (USUARIO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table FASES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FASES (
  TORNEO_ID INT NOT NULL,
  FASE_ID INT NOT NULL,
  DESCRIPCION VARCHAR(45) NOT NULL,
  PRIMARY KEY (TORNEO_ID, FASE_ID),
  INDEX fk_FECHAS_TORNEOS1_idx (TORNEO_ID ASC),
  CONSTRAINT fk_FECHAS_TORNEOS1
    FOREIGN KEY (TORNEO_ID)
    REFERENCES TORNEOS (TORNEO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table CANCHAS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS CANCHAS (
  SEDE_ID INT NOT NULL,
  CANCHA_ID INT NOT NULL,
  DESCRIPCION VARCHAR(45) NOT NULL,
  DEPORTE_ID INT NOT NULL,
  PRECIO INT NOT NULL,
  PRIMARY KEY (SEDE_ID, CANCHA_ID),
  INDEX fk_CANCHAS_DEPORTES1_idx (DEPORTE_ID ASC),
  CONSTRAINT fk_CANCHAS_SEDES1
    FOREIGN KEY (SEDE_ID)
    REFERENCES SEDES (SEDE_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_CANCHAS_DEPORTES1
    FOREIGN KEY (DEPORTE_ID)
    REFERENCES DEPORTES (DEPORTE_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table PARTIDOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS PARTIDOS (
  TORNEO_ID INT NOT NULL,
  FASE_ID INT NOT NULL,
  PARTIDO_ID INT NOT NULL,
  LOCAL_ID INT NOT NULL,
  VISITA_ID INT NOT NULL,
  FECHA DATE NULL,
  HORA TIME(5) NULL,
  ARBITRO_ID VARCHAR(45) NULL,
  PUNTOS_LOCAL INT(3) NULL,
  PUNTOS_VISITA INT(3) NULL,
  LOCAL_OK VARCHAR(1) NULL,
  VISITA_OK VARCHAR(1) NULL,
  SEDE_ID INT NOT NULL,
  CANCHA_ID INT NOT NULL,
  PRIMARY KEY (TORNEO_ID, FASE_ID, PARTIDO_ID),
  INDEX fk_PARTIDOS_EQUIPOS1_idx (LOCAL_ID ASC),
  INDEX fk_PARTIDOS_EQUIPOS2_idx (VISITA_ID ASC),
  INDEX fk_PARTIDOS_USUARIOS1_idx (ARBITRO_ID ASC),
  INDEX fk_PARTIDOS_CANCHAS1_idx (SEDE_ID ASC, CANCHA_ID ASC),
  CONSTRAINT fk_PARTIDOS_FECHAS1
    FOREIGN KEY (TORNEO_ID , FASE_ID)
    REFERENCES FASES (TORNEO_ID , FASE_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_PARTIDOS_EQUIPOS1
    FOREIGN KEY (LOCAL_ID)
    REFERENCES EQUIPOS (EQUIPO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_PARTIDOS_EQUIPOS2
    FOREIGN KEY (VISITA_ID)
    REFERENCES EQUIPOS (EQUIPO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_PARTIDOS_USUARIOS1
    FOREIGN KEY (ARBITRO_ID)
    REFERENCES USUARIOS (USUARIO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_PARTIDOS_CANCHAS1
    FOREIGN KEY (SEDE_ID , CANCHA_ID)
    REFERENCES CANCHAS (SEDE_ID , CANCHA_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table MENSAJES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS MENSAJES (
  MENSAJE_ID INT NOT NULL AUTO_INCREMENT,
  MENSAJE LONGBLOB NOT NULL,
  EMISOR_ID VARCHAR(45) NOT NULL,
  RECEPTOR_ID VARCHAR(45) NULL,
  PARTIDOS_TORNEO_ID INT NULL,
  PARTIDOS_FECHA_ID INT NULL,
  PARTIDOS_PARTIDO_ID INT NULL,
  MENSAJE_ORIGINAL_ID INT NULL,
  PRIMARY KEY (MENSAJE_ID),
  INDEX fk_MENSAJES_USUARIOS1_idx (EMISOR_ID ASC),
  INDEX fk_MENSAJES_USUARIOS2_idx (RECEPTOR_ID ASC),
  INDEX fk_MENSAJES_PARTIDOS1_idx (PARTIDOS_TORNEO_ID ASC, PARTIDOS_FECHA_ID ASC, PARTIDOS_PARTIDO_ID ASC),
  INDEX fk_MENSAJES_MENSAJES1_idx (MENSAJE_ORIGINAL_ID ASC),
  CONSTRAINT fk_MENSAJES_USUARIOS1
    FOREIGN KEY (EMISOR_ID)
    REFERENCES USUARIOS (USUARIO_ID)
    ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_MENSAJES_USUARIOS2
    FOREIGN KEY (RECEPTOR_ID)
    REFERENCES USUARIOS (USUARIO_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_MENSAJES_PARTIDOS1
    FOREIGN KEY (PARTIDOS_TORNEO_ID , PARTIDOS_FECHA_ID , PARTIDOS_PARTIDO_ID)
    REFERENCES PARTIDOS (TORNEO_ID , FASE_ID , PARTIDO_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_MENSAJES_MENSAJES1
    FOREIGN KEY (MENSAJE_ORIGINAL_ID)
    REFERENCES MENSAJES (MENSAJE_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table JUGADORES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS JUGADORES (
  EQUIPO_ID INT NOT NULL,
  JUGADOR_ID VARCHAR(45) NOT NULL,
  PRIMARY KEY (EQUIPO_ID, JUGADOR_ID),
  INDEX fk_EQUIPOS_has_USUARIOS_USUARIOS1_idx (JUGADOR_ID ASC),
  INDEX fk_EQUIPOS_has_USUARIOS_EQUIPOS1_idx (EQUIPO_ID ASC),
  CONSTRAINT fk_EQUIPOS_has_USUARIOS_EQUIPOS1
    FOREIGN KEY (EQUIPO_ID)
    REFERENCES EQUIPOS (EQUIPO_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_EQUIPOS_has_USUARIOS_USUARIOS1
    FOREIGN KEY (JUGADOR_ID)
    REFERENCES USUARIOS (USUARIO_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table ORGANIZADORES
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ORGANIZADORES (
  TORNEO_ID INT NOT NULL,
  ORGANIZADOR_ID VARCHAR(45) NOT NULL,
  ACTIVO VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (TORNEO_ID, ORGANIZADOR_ID),
  INDEX fk_TORNEOS_has_USUARIOS_USUARIOS1_idx (ORGANIZADOR_ID ASC),
  INDEX fk_TORNEOS_has_USUARIOS_TORNEOS1_idx (TORNEO_ID ASC),
  CONSTRAINT fk_TORNEOS_has_USUARIOS_TORNEOS1
    FOREIGN KEY (TORNEO_ID)
    REFERENCES TORNEOS (TORNEO_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_TORNEOS_has_USUARIOS_USUARIOS1
    FOREIGN KEY (ORGANIZADOR_ID)
    REFERENCES USUARIOS (USUARIO_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table EQUIPOS_TORNEO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS EQUIPOS_TORNEO (
  TORNEO_ID INT NOT NULL,
  EQUIPO_ID INT NOT NULL,
  PRIMARY KEY (TORNEO_ID, EQUIPO_ID),
  INDEX fk_TORNEOS_has_EQUIPOS_EQUIPOS1_idx (EQUIPO_ID ASC),
  INDEX fk_TORNEOS_has_EQUIPOS_TORNEOS1_idx (TORNEO_ID ASC),
  CONSTRAINT fk_TORNEOS_has_EQUIPOS_TORNEOS1
    FOREIGN KEY (TORNEO_ID)
    REFERENCES TORNEOS (TORNEO_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_TORNEOS_has_EQUIPOS_EQUIPOS1
    FOREIGN KEY (EQUIPO_ID)
    REFERENCES EQUIPOS (EQUIPO_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table DUENOS
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS DUENOS (
  SEDE_ID INT NOT NULL,
  USUARIO_ID VARCHAR(45) NOT NULL,
  ACTIVO VARCHAR(1) NOT NULL DEFAULT 'Y',
  PRIMARY KEY (SEDE_ID, USUARIO_ID),
  INDEX fk_SEDES_has_USUARIOS_USUARIOS1_idx (USUARIO_ID ASC),
  INDEX fk_SEDES_has_USUARIOS_SEDES1_idx (SEDE_ID ASC),
  CONSTRAINT fk_SEDES_has_USUARIOS_SEDES1
    FOREIGN KEY (SEDE_ID)
    REFERENCES SEDES (SEDE_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_SEDES_has_USUARIOS_USUARIOS1
    FOREIGN KEY (USUARIO_ID)
    REFERENCES USUARIOS (USUARIO_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Table TIPOS_ESTADISTICA
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS TIPOS_ESTADISTICA (
  TIPO_ESTADISTICA_ID INT NOT NULL AUTO_INCREMENT,
  DESCRIPCION VARCHAR(45) NOT NULL,
  PRIMARY KEY (TIPO_ESTADISTICA_ID))
;


-- -----------------------------------------------------
-- Table FICHA_PARTIDO
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS FICHA_PARTIDO (
  TORNEO_ID INT NOT NULL,
  FASE_ID INT NOT NULL,
  PARTIDO_ID INT NOT NULL,
  FICHA_ID INT NOT NULL,
  TIPO_ESTADISTICA_ID CHAR(1) NOT NULL,
  EQUIPO_ID INT NOT NULL,
  JUGADOR_ID VARCHAR(45) NOT NULL,
  PRIMARY KEY (TORNEO_ID, FASE_ID, PARTIDO_ID, FICHA_ID),
  INDEX fk_FICHA_PARTIDO_TIPOS_ESTADISTICA1_idx (TIPO_ESTADISTICA_ID ASC),
  INDEX fk_FICHA_PARTIDO_JUGADORES1_idx (EQUIPO_ID ASC, JUGADOR_ID ASC),
  CONSTRAINT fk_FICHA_PARTIDO_PARTIDOS1
    FOREIGN KEY (TORNEO_ID , FASE_ID , PARTIDO_ID)
    REFERENCES PARTIDOS (TORNEO_ID , FASE_ID , PARTIDO_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_FICHA_PARTIDO_TIPOS_ESTADISTICA1
    FOREIGN KEY (TIPO_ESTADISTICA_ID)
    REFERENCES TIPOS_ESTADISTICA (TIPO_ESTADISTICA_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT fk_FICHA_PARTIDO_JUGADORES1
    FOREIGN KEY (EQUIPO_ID , JUGADOR_ID)
    REFERENCES JUGADORES (EQUIPO_ID , JUGADOR_ID)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
;


-- -----------------------------------------------------
-- Data for table PAISES
-- -----------------------------------------------------
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ABW', 'Aruba', 'AW');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('AFG', 'Afghanistan', 'AF');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('AGO', 'Angola', 'AO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('AIA', 'Anguilla', 'AI');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ALB', 'Albania', 'AL');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('AND', 'Andorra', 'AD');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ANT', 'Netherlands Antilles', 'AN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ARE', 'United Arab Emirates', 'AE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ARG', 'Argentina', 'AR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ARM', 'Armenia', 'AM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ASM', 'American Samoa', 'AS');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ATA', 'Antarctica', 'AQ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ATF', 'French Southern territories', 'TF');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ATG', 'Antigua and Barbuda', 'AG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('AUS', 'Australia', 'AU');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('AUT', 'Austria', 'AT');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('AZE', 'Azerbaijan', 'AZ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BDI', 'Burundi', 'BI');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BEL', 'Belgium', 'BE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BEN', 'Benin', 'BJ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BFA', 'Burkina Faso', 'BF');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BGD', 'Bangladesh', 'BD');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BGR', 'Bulgaria', 'BG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BHR', 'Bahrain', 'BH');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BHS', 'Bahamas', 'BS');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BIH', 'Bosnia and Herzegovina', 'BA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BLR', 'Belarus', 'BY');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BLZ', 'Belize', 'BZ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BMU', 'Bermuda', 'BM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BOL', 'Bolivia', 'BO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BRA', 'Brazil', 'BR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BRB', 'Barbados', 'BB');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BRN', 'Brunei', 'BN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BTN', 'Bhutan', 'BT');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BVT', 'Bouvet Island', 'BV');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('BWA', 'Botswana', 'BW');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CAF', 'Central African Republic', 'CF');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CAN', 'Canada', 'CA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CCK', 'Cocos (Keeling) Islands', 'CC');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CHE', 'Switzerland', 'CH');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CHL', 'Chile', 'CL');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CHN', 'China', 'CN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CIV', 'Cï¿½te dï¿½Ivoire', 'CI');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CMR', 'Cameroon', 'CM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('COD', 'Congo, The Democratic Republic of the', 'CD');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('COG', 'Congo', 'CG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('COK', 'Cook Islands', 'CK');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('COL', 'Colombia', 'CO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('COM', 'Comoros', 'KM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CPV', 'Cape Verde', 'CV');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CRI', 'Costa Rica', 'CR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CUB', 'Cuba', 'CU');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CXR', 'Christmas Island', 'CX');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CYM', 'Cayman Islands', 'KY');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CYP', 'Cyprus', 'CY');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('CZE', 'Czech Republic', 'CZ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('DEU', 'Germany', 'DE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('DJI', 'Djibouti', 'DJ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('DMA', 'Dominica', 'DM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('DNK', 'Denmark', 'DK');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('DOM', 'Dominican Republic', 'DO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('DZA', 'Algeria', 'DZ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ECU', 'Ecuador', 'EC');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('EGY', 'Egypt', 'EG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ERI', 'Eritrea', 'ER');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ESH', 'Western Sahara', 'EH');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ESP', 'Spain', 'ES');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('EST', 'Estonia', 'EE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ETH', 'Ethiopia', 'ET');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('FIN', 'Finland', 'FI');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('FJI', 'Fiji Islands', 'FJ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('FLK', 'Falkland Islands', 'FK');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('FRA', 'France', 'FR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('FRO', 'Faroe Islands', 'FO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('FSM', 'Micronesia, Federated States of', 'FM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GAB', 'Gabon', 'GA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GBR', 'United Kingdom', 'GB');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GEO', 'Georgia', 'GE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GHA', 'Ghana', 'GH');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GIB', 'Gibraltar', 'GI');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GIN', 'Guinea', 'GN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GLP', 'Guadeloupe', 'GP');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GMB', 'Gambia', 'GM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GNB', 'Guinea-Bissau', 'GW');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GNQ', 'Equatorial Guinea', 'GQ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GRC', 'Greece', 'GR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GRD', 'Grenada', 'GD');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GRL', 'Greenland', 'GL');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GTM', 'Guatemala', 'GT');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GUF', 'French Guiana', 'GF');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GUM', 'Guam', 'GU');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('GUY', 'Guyana', 'GY');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('HKG', 'Hong Kong', 'HK');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('HMD', 'Heard Island and McDonald Islands', 'HM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('HND', 'Honduras', 'HN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('HRV', 'Croatia', 'HR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('HTI', 'Haiti', 'HT');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('HUN', 'Hungary', 'HU');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('IDN', 'Indonesia', 'ID');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('IND', 'India', 'IN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('IOT', 'British Indian Ocean Territory', 'IO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('IRL', 'Ireland', 'IE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('IRN', 'Iran', 'IR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('IRQ', 'Iraq', 'IQ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ISL', 'Iceland', 'IS');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ISR', 'Israel', 'IL');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ITA', 'Italy', 'IT');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('JAM', 'Jamaica', 'JM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('JOR', 'Jordan', 'JO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('JPN', 'Japan', 'JP');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('KAZ', 'Kazakstan', 'KZ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('KEN', 'Kenya', 'KE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('KGZ', 'Kyrgyzstan', 'KG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('KHM', 'Cambodia', 'KH');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('KIR', 'Kiribati', 'KI');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('KNA', 'Saint Kitts and Nevis', 'KN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('KOR', 'South Korea', 'KR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('KWT', 'Kuwait', 'KW');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('LAO', 'Laos', 'LA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('LBN', 'Lebanon', 'LB');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('LBR', 'Liberia', 'LR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('LBY', 'Libyan Arab Jamahiriya', 'LY');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('LCA', 'Saint Lucia', 'LC');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('LIE', 'Liechtenstein', 'LI');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('LKA', 'Sri Lanka', 'LK');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('LSO', 'Lesotho', 'LS');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('LTU', 'Lithuania', 'LT');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('LUX', 'Luxembourg', 'LU');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('LVA', 'Latvia', 'LV');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MAC', 'Macao', 'MO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MAR', 'Morocco', 'MA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MCO', 'Monaco', 'MC');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MDA', 'Moldova', 'MD');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MDG', 'Madagascar', 'MG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MDV', 'Maldives', 'MV');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MEX', 'Mexico', 'MX');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MHL', 'Marshall Islands', 'MH');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MKD', 'Macedonia', 'MK');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MLI', 'Mali', 'ML');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MLT', 'Malta', 'MT');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MMR', 'Myanmar', 'MM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MNG', 'Mongolia', 'MN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MNP', 'Northern Mariana Islands', 'MP');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MOZ', 'Mozambique', 'MZ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MRT', 'Mauritania', 'MR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MSR', 'Montserrat', 'MS');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MTQ', 'Martinique', 'MQ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MUS', 'Mauritius', 'MU');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MWI', 'Malawi', 'MW');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MYS', 'Malaysia', 'MY');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('MYT', 'Mayotte', 'YT');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NAM', 'Namibia', 'NA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NCL', 'New Caledonia', 'NC');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NER', 'Niger', 'NE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NFK', 'Norfolk Island', 'NF');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NGA', 'Nigeria', 'NG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NIC', 'Nicaragua', 'NI');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NIU', 'Niue', 'NU');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NLD', 'Netherlands', 'NL');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NOR', 'Norway', 'NO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NPL', 'Nepal', 'NP');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NRU', 'Nauru', 'NR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('NZL', 'New Zealand', 'NZ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('OMN', 'Oman', 'OM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PAK', 'Pakistan', 'PK');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PAN', 'Panama', 'PA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PCN', 'Pitcairn', 'PN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PER', 'Peru', 'PE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PHL', 'Philippines', 'PH');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PLW', 'Palau', 'PW');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PNG', 'Papua New Guinea', 'PG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('POL', 'Poland', 'PL');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PRI', 'Puerto Rico', 'PR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PRK', 'North Korea', 'KP');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PRT', 'Portugal', 'PT');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PRY', 'Paraguay', 'PY');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PSE', 'Palestine', 'PS');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('PYF', 'French Polynesia', 'PF');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('QAT', 'Qatar', 'QA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('REU', 'Rï¿½union', 'RE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ROM', 'Romania', 'RO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('RUS', 'Russian Federation', 'RU');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('RWA', 'Rwanda', 'RW');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SAU', 'Saudi Arabia', 'SA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SDN', 'Sudan', 'SD');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SEN', 'Senegal', 'SN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SGP', 'Singapore', 'SG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SGS', 'South Georgia and the South Sandwich Islands', 'GS');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SHN', 'Saint Helena', 'SH');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SJM', 'Svalbard and Jan Mayen', 'SJ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SLB', 'Solomon Islands', 'SB');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SLE', 'Sierra Leone', 'SL');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SLV', 'El Salvador', 'SV');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SMR', 'San Marino', 'SM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SOM', 'Somalia', 'SO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SPM', 'Saint Pierre and Miquelon', 'PM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('STP', 'Sao Tome and Principe', 'ST');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SUR', 'Suriname', 'SR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SVK', 'Slovakia', 'SK');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SVN', 'Slovenia', 'SI');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SWE', 'Sweden', 'SE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SWZ', 'Swaziland', 'SZ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SYC', 'Seychelles', 'SC');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('SYR', 'Syria', 'SY');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TCA', 'Turks and Caicos Islands', 'TC');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TCD', 'Chad', 'TD');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TGO', 'Togo', 'TG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('THA', 'Thailand', 'TH');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TJK', 'Tajikistan', 'TJ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TKL', 'Tokelau', 'TK');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TKM', 'Turkmenistan', 'TM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TMP', 'East Timor', 'TP');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TON', 'Tonga', 'TO');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TTO', 'Trinidad and Tobago', 'TT');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TUN', 'Tunisia', 'TN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TUR', 'Turkey', 'TR');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TUV', 'Tuvalu', 'TV');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TWN', 'Taiwan', 'TW');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('TZA', 'Tanzania', 'TZ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('UGA', 'Uganda', 'UG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('UKR', 'Ukraine', 'UA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('UMI', 'United States Minor Outlying Islands', 'UM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('URY', 'Uruguay', 'UY');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('USA', 'United States', 'US');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('UZB', 'Uzbekistan', 'UZ');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('VAT', 'Holy See (Vatican City State)', 'VA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('VCT', 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('VEN', 'Venezuela', 'VE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('VGB', 'Virgin Islands, British', 'VG');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('VIR', 'Virgin Islands, U.S.', 'VI');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('VNM', 'Vietnam', 'VN');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('VUT', 'Vanuatu', 'VU');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('WLF', 'Wallis and Futuna', 'WF');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('WSM', 'Samoa', 'WS');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('YEM', 'Yemen', 'YE');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('YUG', 'Yugoslavia', 'YU');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ZAF', 'South Africa', 'ZA');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ZMB', 'Zambia', 'ZM');
INSERT INTO PAISES (PAIS_ID, PAIS, ISO) VALUES('ZWE', 'Zimbabwe', 'ZW');


-- -----------------------------------------------------
-- Data for table PAISES
-- -----------------------------------------------------
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'BUE', 'Buenos Aires');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'CAT', 'Catamarca');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'CHA', 'Chaco');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'CHU', 'Chubut');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'CBA', 'Córdoba');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'COR', 'Corrientes');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'CAP', 'Capital Federal');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'ENR', 'Entre Ríos');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'FOR', 'Formosa');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'JUJ', 'Jujuy');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'LPA', 'La Pampa');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'LRI', 'La Rioja');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'MEN', 'Mendoza');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'MIS', 'Misiones');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'NEU', 'Neuquén');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'RNE', 'Río Negro');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'SAL', 'Salta');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'SJU', 'San Juan');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'SLU', 'San Luis');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'SCR', 'Santa Cruz');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'SFE', 'Santa Fe');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'SDE', 'Santiago del Estero');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'TDF', 'Tierra del Fuego');
INSERT INTO PROVINCIAS (PAIS_ID , PROVINCIA_ID ,PROVINCIA ) VALUES('ARG', 'TUC', 'Tucumán');

-- -----------------------------------------------------
-- Data for table DEPORTES
-- -----------------------------------------------------
INSERT INTO DEPORTES (DEPORTE_ID, DESCRIPCION, MAX_JUGADORES) VALUES (1, 'Futbol 5', 10);
INSERT INTO DEPORTES (DEPORTE_ID, DESCRIPCION, MAX_JUGADORES) VALUES (2, 'Futbol 11', 18);
INSERT INTO DEPORTES (DEPORTE_ID, DESCRIPCION, MAX_JUGADORES) VALUES (3, 'Tenis Individual', 1);
INSERT INTO DEPORTES (DEPORTE_ID, DESCRIPCION, MAX_JUGADORES) VALUES (4, 'Tenis Dobles', 2);
INSERT INTO DEPORTES (DEPORTE_ID, DESCRIPCION, MAX_JUGADORES) VALUES (5, 'Basket', 12);
INSERT INTO DEPORTES (DEPORTE_ID, DESCRIPCION, MAX_JUGADORES) VALUES (6, 'Volley', 12);
INSERT INTO DEPORTES (DEPORTE_ID, DESCRIPCION, MAX_JUGADORES) VALUES (7, 'Paddle Individual', 1);
INSERT INTO DEPORTES (DEPORTE_ID, DESCRIPCION, MAX_JUGADORES) VALUES (8, 'Paddle Dobles', 2);
INSERT INTO DEPORTES (DEPORTE_ID, DESCRIPCION, MAX_JUGADORES) VALUES (9, 'Rugby', 35);
INSERT INTO DEPORTES (DEPORTE_ID, DESCRIPCION, MAX_JUGADORES) VALUES (10, 'Golf', 1);



-- -----------------------------------------------------
-- Data for table TIPOS_TORNEO
-- -----------------------------------------------------
INSERT INTO TIPOS_TORNEO (TIPO_TORNEO_ID, DESCRIPCION) VALUES ('L', 'Liga');
INSERT INTO TIPOS_TORNEO (TIPO_TORNEO_ID, DESCRIPCION) VALUES ('C', 'Copa');
INSERT INTO TIPOS_TORNEO (TIPO_TORNEO_ID, DESCRIPCION) VALUES ('T', 'Torneo Ida y Vuelta');




-- -----------------------------------------------------
-- Data for table SEDES
-- -----------------------------------------------------
INSERT INTO SEDES (SEDE_ID, NOMBRE, PAIS_ID, PROVINCIA_ID, CODIGO_POSTAL, CALLE, ALTURA, TELEFONO, DETALLES) VALUES (1, 'La Popular', 'ARG', 'BUE', '1752', 'Costa Rica', 80, '4655-2212', NULL);



-- -----------------------------------------------------
-- Data for table TORNEOS
-- -----------------------------------------------------
INSERT INTO TORNEOS (TORNEO_ID, NOMBRE, DEPORTE_ID, TIPO_TORNEO_ID, CANTIDAD_EQUIPOS, FECHA_INICIO, SEDE_ID) VALUES (1, 'Torneo MAdero', 1, 'L', 2, NULL, 1);



-- -----------------------------------------------------
-- Data for table USUARIOS
-- -----------------------------------------------------
INSERT INTO USUARIOS (USUARIO_ID, NOMBRE, APELLIDO, ALIAS, PASSWORD, ACTIVO, TELEFONO) VALUES ('facundo1', 'Facundo', 'Salerno', DEFAULT, '1234', '1', '4655-1231');
INSERT INTO USUARIOS (USUARIO_ID, NOMBRE, APELLIDO, ALIAS, PASSWORD, ACTIVO, TELEFONO) VALUES ('facundo2', 'Facundo', 'Salerno', '', '1234', '1', '4532-3123');
INSERT INTO USUARIOS (USUARIO_ID, NOMBRE, APELLIDO, ALIAS, PASSWORD, ACTIVO, TELEFONO) VALUES ('facundo3', 'Facundo', 'Salerno', DEFAULT, '1234', '1', '1123-1231');
INSERT INTO USUARIOS (USUARIO_ID, NOMBRE, APELLIDO, ALIAS, PASSWORD, ACTIVO, TELEFONO) VALUES ('facundo4', 'Facundo', 'Salerno', DEFAULT, '1234', '1', '1231-4123');
INSERT INTO USUARIOS (USUARIO_ID, NOMBRE, APELLIDO, ALIAS, PASSWORD, ACTIVO, TELEFONO) VALUES ('facundo5', 'Facundo', 'Salerno', DEFAULT, '1234', '1', '1233-1232');
INSERT INTO USUARIOS (USUARIO_ID, NOMBRE, APELLIDO, ALIAS, PASSWORD, ACTIVO, TELEFONO) VALUES ('gonzalo1', 'Gonzalo', 'Vicens', DEFAULT, '2345', '1', '3241-1232');
INSERT INTO USUARIOS (USUARIO_ID, NOMBRE, APELLIDO, ALIAS, PASSWORD, ACTIVO, TELEFONO) VALUES ('gonzalo2', 'Gonzalo', 'Vicens', DEFAULT, '2345', '1', '3241-1232');
INSERT INTO USUARIOS (USUARIO_ID, NOMBRE, APELLIDO, ALIAS, PASSWORD, ACTIVO, TELEFONO) VALUES ('gonzalo3', 'Gonzalo', 'Vicens', DEFAULT, '2345', '1', '3241-1232');
INSERT INTO USUARIOS (USUARIO_ID, NOMBRE, APELLIDO, ALIAS, PASSWORD, ACTIVO, TELEFONO) VALUES ('gonzalo4', 'Gonzalo', 'Vicens', DEFAULT, '2345', '1', '3241-1232');
INSERT INTO USUARIOS (USUARIO_ID, NOMBRE, APELLIDO, ALIAS, PASSWORD, ACTIVO, TELEFONO) VALUES ('gonzalo5', 'Gonzalo', 'Vicens', DEFAULT, '2345', '1', '3241-1232');



-- -----------------------------------------------------
-- Data for table EQUIPOS
-- -----------------------------------------------------
INSERT INTO EQUIPOS (EQUIPO_ID, NOMBRE, CAPITAN_ID, ACTIVO) VALUES (1, 'Equipo Facu', '1', '1');
INSERT INTO EQUIPOS (EQUIPO_ID, NOMBRE, CAPITAN_ID, ACTIVO) VALUES (2, 'Equipo Gonza', '6', '1');



-- -----------------------------------------------------
-- Data for table FASES
-- -----------------------------------------------------
INSERT INTO FASES (TORNEO_ID, FASE_ID, DESCRIPCION) VALUES (1, 1, 'Fecha 1');



-- -----------------------------------------------------
-- Data for table CANCHAS
-- -----------------------------------------------------
INSERT INTO CANCHAS (SEDE_ID, CANCHA_ID, DESCRIPCION, DEPORTE_ID, PRECIO) VALUES (1, 1, 'La Canchita', 1, 300);



-- -----------------------------------------------------
-- Data for table PARTIDOS
-- -----------------------------------------------------
INSERT INTO PARTIDOS (TORNEO_ID, FASE_ID, PARTIDO_ID, LOCAL_ID, VISITA_ID, FECHA, HORA, ARBITRO_ID, PUNTOS_LOCAL, PUNTOS_VISITA, LOCAL_OK, VISITA_OK, SEDE_ID, CANCHA_ID) VALUES (1, 1, 1, 1, 2, '15-10-2016', '21:00', NULL, 1, 2, 'Y', 'Y', 1, 1);



-- -----------------------------------------------------
-- Data for table JUGADORES
-- -----------------------------------------------------
INSERT INTO JUGADORES (EQUIPO_ID, JUGADOR_ID) VALUES (1, 'facundo1');
INSERT INTO JUGADORES (EQUIPO_ID, JUGADOR_ID) VALUES (1, 'facundo2');
INSERT INTO JUGADORES (EQUIPO_ID, JUGADOR_ID) VALUES (1, 'facundo3');
INSERT INTO JUGADORES (EQUIPO_ID, JUGADOR_ID) VALUES (1, 'facundo4');
INSERT INTO JUGADORES (EQUIPO_ID, JUGADOR_ID) VALUES (1, 'facundo5');
INSERT INTO JUGADORES (EQUIPO_ID, JUGADOR_ID) VALUES (2, 'gonzalo1');
INSERT INTO JUGADORES (EQUIPO_ID, JUGADOR_ID) VALUES (2, 'gonzalo2');
INSERT INTO JUGADORES (EQUIPO_ID, JUGADOR_ID) VALUES (2, 'gonzalo3');
INSERT INTO JUGADORES (EQUIPO_ID, JUGADOR_ID) VALUES (2, 'gonzalo4');
INSERT INTO JUGADORES (EQUIPO_ID, JUGADOR_ID) VALUES (2, 'gonzalo5');



-- -----------------------------------------------------
-- Data for table ORGANIZADORES
-- -----------------------------------------------------
INSERT INTO ORGANIZADORES (TORNEO_ID, ORGANIZADOR_ID, ACTIVO) VALUES (1, 'facundo1', '1');



-- -----------------------------------------------------
-- Data for table EQUIPOS_TORNEO
-- -----------------------------------------------------
INSERT INTO EQUIPOS_TORNEO (TORNEO_ID, EQUIPO_ID) VALUES (1, 1);
INSERT INTO EQUIPOS_TORNEO (TORNEO_ID, EQUIPO_ID) VALUES (1, 2);



-- -----------------------------------------------------
-- Data for table DUENOS
-- -----------------------------------------------------
INSERT INTO DUENOS (SEDE_ID, USUARIO_ID, ACTIVO) VALUES (1, 'facundo1', '1');



-- -----------------------------------------------------
-- Data for table TIPOS_ESTADISTICA
-- -----------------------------------------------------
INSERT INTO TIPOS_ESTADISTICA (TIPO_ESTADISTICA_ID, DESCRIPCION) VALUES (1, 'Gol');
INSERT INTO TIPOS_ESTADISTICA (TIPO_ESTADISTICA_ID, DESCRIPCION) VALUES (2, 'Puntos');
INSERT INTO TIPOS_ESTADISTICA (TIPO_ESTADISTICA_ID, DESCRIPCION) VALUES (3, 'Set');
INSERT INTO TIPOS_ESTADISTICA (TIPO_ESTADISTICA_ID, DESCRIPCION) VALUES (4, 'Tarjeta Amarilla');
INSERT INTO TIPOS_ESTADISTICA (TIPO_ESTADISTICA_ID, DESCRIPCION) VALUES (5, 'Tarjeta Roja');
INSERT INTO TIPOS_ESTADISTICA (TIPO_ESTADISTICA_ID, DESCRIPCION) VALUES (6, 'Tarjeta Verde');



-- -----------------------------------------------------
-- Data for table FICHA_PARTIDO
-- -----------------------------------------------------
INSERT INTO FICHA_PARTIDO (TORNEO_ID, FASE_ID, PARTIDO_ID, FICHA_ID, TIPO_ESTADISTICA_ID, EQUIPO_ID, JUGADOR_ID) VALUES (1, 1, 1, 1, '1', 1, 'facundo3');
INSERT INTO FICHA_PARTIDO (TORNEO_ID, FASE_ID, PARTIDO_ID, FICHA_ID, TIPO_ESTADISTICA_ID, EQUIPO_ID, JUGADOR_ID) VALUES (1, 1, 1, 2, '4', 2, 'gonzalo1');
INSERT INTO FICHA_PARTIDO (TORNEO_ID, FASE_ID, PARTIDO_ID, FICHA_ID, TIPO_ESTADISTICA_ID, EQUIPO_ID, JUGADOR_ID) VALUES (1, 1, 1, 3, '1', 2, 'gonzalo5');
INSERT INTO FICHA_PARTIDO (TORNEO_ID, FASE_ID, PARTIDO_ID, FICHA_ID, TIPO_ESTADISTICA_ID, EQUIPO_ID, JUGADOR_ID) VALUES (1, 1, 1, 4, '1', 2, 'gonzalo3');


